runtime: python37

handlers:
    # This configures Google App Engine to serve the files in the app's
    # static directory.
     - url: /static
       static_dir: static

     - url: /.*
       script: auto


env_variables:
    DEBUG: 'false'
    INSTANCE_CONNECTION_NAME: 'tools-for-analytics-308307:us-east1:squirrel'
    PGDATABASE: 'postgres'
    PGUSER: 'postgres'
    PGPASSWORD: 'N0Fvx3Cl3feMipF6'
    SECRET_KEY: '#_$4p!+as4g(9_1_q7k$6upct8(3-1xh++6jt9-4$g(-429of9'
    GS_BUCKET_NAME: 'tools-for-analytics-308307.appspot.com'
    GOOGLE_APPLICATION_CREDENTIALS: 'service-account-key.json'
