# Generated by Django 3.0.7 on 2021-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(blank=True, decimal_places=100, help_text='Longitude', max_digits=100, max_length=100)),
                ('Y', models.DecimalField(blank=True, decimal_places=100, help_text='Latitude', max_digits=100, max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shifting time', max_length=15)),
                ('Date', models.DateField(help_text='Specific date')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of Squirrel', max_length=15)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary fur color of the squirrel', max_length=15)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='sighter instructed squirrel location', max_length=30)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific location of the squirrel', max_length=100)),
                ('Running', models.BooleanField(default=False, help_text='Is it running', max_length=15)),
                ('Chasing', models.BooleanField(default=False, help_text='Is it chasing', max_length=15)),
                ('Climbing', models.BooleanField(default=False, help_text='Is it climbing', max_length=15)),
                ('Eating', models.BooleanField(default=False, help_text='Is it eating', max_length=15)),
                ('Foraging', models.BooleanField(default=False, help_text='Is it foraging', max_length=15)),
                ('Other_Activities', models.CharField(blank=True, help_text='Specific activity the squirrel is doing', max_length=100)),
                ('Kuks', models.BooleanField(default=False, help_text='Whether kuks', max_length=15)),
                ('Quaas', models.BooleanField(default=False, help_text='Whether quaas', max_length=15)),
                ('Moans', models.BooleanField(default=False, help_text='Whether moans', max_length=15)),
                ('Tail_flags', models.BooleanField(default=False, help_text='Whether tail flags', max_length=15)),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Whether tail twitches', max_length=15)),
                ('Approaches', models.BooleanField(default=False, help_text='Whether approaching to human being', max_length=15)),
                ('Indifferent', models.BooleanField(default=False, help_text='Whether showing indifferent to human being', max_length=15)),
                ('Runs_from', models.BooleanField(default=False, help_text='Whether runing from human being', max_length=15)),
            ],
        ),
    ]
